#!/usr/bin/env bash
#school file
if [ -e school ]; then
  echo "school file exists"
  
  if [ -f school ]; then
    if [ ! -s school ]; then
      echo "school file is empty"
    else
      echo "school file is not empty"
    fi
    echo "school is a regular file"
  else
    if [ ! -s school ]; then
      echo "school file is empty"
    else
      echo "school file is not empty"
    fi
  fi

else
  echo "school file does not exist"
fi
