#!/usr/bin/env bash
#list your processes
ps -eo user,start,cmd --sort=start_time --forest | awk '
BEGIN {
    printf "%-8s %-10s %s\n", "USER", "STARTED", "CMD"
}
NR > 1 {
    printf "%-8s %-10s %s\n", $1, $2, $3
}
'
