#!/usr/bin/env bash
#list your processes
ps -ef --forest | awk '
NR==1 {
    printf "%-10s %-5s %-4s %-4s %-6s %-6s %-8s %-5s %-8s %s\n", "USER", "PID", "%CPU", "%MEM", "VSZ", "RSS", "TTY", "STAT", "START", "COMMAND"
}
NR>1 {
    printf "%-10s %-5s %-4s %-4s %-6s %-6s %-8s %-5s %-8s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, substr($0, index($0,$10))
}
'
