#!/usr/bin/env bash
#list your processes
ps -ef --forest | awk '
NR==1 {
    printf "%-10s %-5s %-4s %-4s %-6s %-6s %-8s %-5s %-15s %s\n", "USER", "PID", "%CPU", "%MEM", "VSZ", "RSS", "TTY", "STAT", "START", "COMMAND"
}
NR>1 {
    cmd=$0
    for (i=10; i<=NF; i++) {
        cmd=cmd " " $i
    }
    printf "%-10s %-5s %-4s %-4s %-6s %-6s %-8s %-5s %-15s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, cmd
}
'
