#!/usr/bin/env bash
#process and pid
function love() {
    rm /var/run/myscript.pid
    exit
}

trap "echo I hate the kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT

echo $$ >> /var/run/myscript.pid
while true ; do
    echo To infinity and beyond;
done
