#!/usr/bin/env bash
#manage my process
PROCESS_NAME="manage_my_process"
PID_FILE="/var/run/my_process.pid"
SCRIPT_PATH="/alu-shell/processes_and_signals/manage_my_process"
case "$1" in
    start)
        if [ -f $PID_FILE ]; then
            echo "$PROCESS_NAME is already running."
        else
            nohup $SCRIPT_PATH & echo $! > $PID_FILE
            echo "$PROCESS_NAME started"
        fi
        ;;
    stop)
        if [ -f $PID_FILE ]; then
            PID=$(cat $PID_FILE)
            kill $PID
            rm $PID_FILE
            echo "$PROCESS_NAME stopped"
        else
            echo "$PROCESS_NAME is not running."
        fi
        ;;
    restart)
        if [ -f $PID_FILE ]; then
            PID=$(cat $PID_FILE)
            kill $PID
            rm $PID_FILE
        fi
        nohup $SCRIPT_PATH & echo $! > $PID_FILE
        echo "$PROCESS_NAME restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
