#!/usr/bin/env bash
#manage my process
PROCESS_NAME="manage_my_process"
PID_FILE="/var/run/my_process.pid"
SCRIPT_PATH="/alu-shell/processes_and_signals/manage_my_process"

case "$1" in
    start)
        if [ -f "$PID_FILE" ]; then
            echo "$PROCESS_NAME is already running."
            exit 1
        fi
        $SCRIPT_PATH &
        echo $! > "$PID_FILE"
        echo "$PROCESS_NAME started"
        ;;
    stop)
        if [ ! -f "$PID_FILE" ]; then
            echo "$PROCESS_NAME is not running."
            exit 1
        fi
        kill -9 $(cat "$PID_FILE")
        rm -f "$PID_FILE"
        echo "$PROCESS_NAME stopped"
        ;;
    restart)
        if [ -f "$PID_FILE" ]; then
            kill -9 $(cat "$PID_FILE")
            rm -f "$PID_FILE"
        fi
        $SCRIPT_PATH &
        echo $! > "$PID_FILE"
        echo "$PROCESS_NAME restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
